function analysis=cuplDrawPlots(analysis,plots)
%CUPLDRAWPLOTS  Draws plots of the analysed data
%
%   CUPLDRAWPLOTS(ANALYSIS) Draws all plots of the analysed data.
%
%   CUPLANALYSEFILES(ANALYSIS,PLOTS) Draws only the plots specified by the
%   string ids in cell array PLOTS.
%
% Copyright (c) 2010 Elina Vladimirou
% Copyright (c) 2013 Jonathan Armond

if nargin<1
    error('No analysis struct supplied.');
end

% Alias analysis.
an = analysis;

% Defaults.
if nargin<2
  validPlots = cuplValidPlots(an);
  plots = validPlots(:,2);
end

if ~isfield(an,'plotOptions')
  an = cuplAskPlotParameters(an,plots);
end

close all;

% Plot autocorrelations.
if ismember('avgauto',plots)
  autocorrs = an.autocorrs;
  plotOptions = {'Colours',an.plotOptions.colours,...
                 'MaxTime',an.plotOptions.maxTime};

  % Plot dx.
  cuplPlotCorrelation(...
    autocorrs.t,autocorrs.sisters.m_dx,...
    autocorrs.sisters.e_dx,plotOptions{:},...
    'PlotTitle','Average autocorrelation of pair centres, dx',...
    'Output',cuplMakeFigureName(an,'avg-autocorr-dx'));

  % Plot delta separation.
  cuplPlotCorrelation(...
    autocorrs.t,autocorrs.sisters.m_dd,...
    autocorrs.sisters.e_dd,plotOptions{:},...
    'PlotTitle','Average autocorrelation of sister pair breathing',...
    'Output',cuplMakeFigureName(an,'avg-autocorr-breathing'));
end

% Plot crosscorrelations.
if ismember('avgcross',plots)
  corrs = an.crosscorrs;
  plotOptions = {'Colours',an.plotOptions.colours,...
                 'MaxTime',an.plotOptions.maxTime};

  % Plot non-sister individuals dx.
  cuplPlotCorrelation(...
    corrs.t,corrs.sisters.ind.m_dx,corrs.sisters.ind.e_dx,plotOptions{:},...
    'PlotTitle','Average crosscorrelation of non-sisters, dx',...
    'Output',cuplMakeFigureName(an,'avg-crosscorr-nonsisters-dx'));
  
  % Plot sister individuals dx.
  cuplPlotCorrelation(...
    corrs.t,corrs.sisters.sister.m_dx,corrs.sisters.sister.e_dx,plotOptions{:},...
    'PlotTitle','Average crosscorrelation of sisters, dx',...
    'Output',cuplMakeFigureName(an,'avg-crosscorr-sisters-dx'));
  
  % Plot pair centres dx.
  cuplPlotCorrelation(...
    corrs.t,corrs.sisters.pair.m_dx,corrs.sisters.pair.e_dx,plotOptions{:},...
    'PlotTitle','Average crosscorrelation of pair centres, dx',...
    'Output',cuplMakeFigureName(an,'avg-crosscorr-pairs-dx'));

  % Plot avg crosscorrelation of nearest neighbours dx.
  cuplPlotCorrelation(...
    corrs.t,corrs.sisters.ind.near_m_dx,...
    corrs.sisters.ind.near_e_dx,plotOptions{:},...
    'PlotTitle','Average crosscorrelation of nearest neighbours, Dx',...
    'Output',cuplMakeFigureName(an,'avg-crosscorr-near-dx'));

  % Plot avg crosscorrelation of furthest neighbours dx.
  cuplPlotCorrelation(...
    corrs.t,corrs.sisters.ind.far_m_dx,...
    corrs.sisters.ind.far_e_dx,plotOptions{:},...
    'PlotTitle','Average crosscorrelation of furthest neighbours, Dx',...
    'Output',cuplMakeFigureName(an,'avg-crosscorr-far-dx'));
end

% Plot correlations by distance.
if ismember('corrdist',plots)
  dists = an.distances.sisters;
  corrs = an.crosscorrs.sisters;
  corrdist = an.corrdist.sisters;
  lagzero = ceil(size(an.crosscorrs.sisters.ind.dx,1)/2);
  plotOptions = {'Colours',an.plotOptions.colours};
  
  % Plot individuals (sister and non-sister) dx.
  cuplPlotScatter(...
    {dists.ind.d,dists.sister.d},...
    {corrs.ind.dx(lagzero,:)', corrs.sister.dx(lagzero,:)'},...
    plotOptions{:},'PlotTitle','Correlations between all kinetchores, dx',...
    'Output',cuplMakeFigureName(an,'corrdist-all'));

  % Plot pair centres dx.
  cuplPlotScatter(...
    dists.pair.d,corrs.pair.dx(lagzero,:)',...
    plotOptions{:},'PlotTitle','Correlation of pair centres, dx',...
    'Output',cuplMakeFigureName(an,'corrdist-centres'));

  % Plot individuals (sister and non-sister) cross by dist, dx.
  cuplPlotBins(...
    corrdist.ind.centres,...
    [corrdist.ind.m(:,lagzero),corrdist.sister.m(:,lagzero)],...
    [corrdist.ind.e(:,lagzero),corrdist.sister.e(:,lagzero)],plotOptions{:},...
    'PlotTitle','Correlation by distance of all kinetochores, dx',...
    'Output',cuplMakeFigureName(an,'corrdist-all-bins'));
  
  % Plot pair centres cross by dist, dx.
  cuplPlotBins(...
    corrdist.pair.centres,corrdist.pair.m(:,lagzero),...
    corrdist.pair.e(:,lagzero),plotOptions{:},...
    'PlotTitle','Correlation by distance of pair centres, dx',...
    'Output',cuplMakeFigureName(an,'corrdist-centres-bins'));

  % Alternate lag
  lag = lagzero+1;
  
  % Plot alt lag individuals (sister and non-sister) dx.
  cuplPlotScatter(...
    {dists.ind.d,dists.sister.d},...
    {corrs.ind.dx(lag,:)', corrs.sister.dx(lag,:)'},...
    plotOptions{:},'PlotTitle',['Correlations between all kinetchores, dx, lag ' num2str(lag-1)],...
    'Output',cuplMakeFigureName(an,num2str(lag-1,'corrdist-lag%d-all')));

  % Plot alt lag pair centres dx.
  cuplPlotScatter(...
    dists.pair.d,corrs.pair.dx(lag,:)',...
    plotOptions{:},'PlotTitle',['Correlation of pair centres, dx, lag ' num2str(lag-1)],...
    'Output',cuplMakeFigureName(an,num2str(lag-1,'corrdist-lag%d-centres')));
  
  % Plot individuals (sister and non-sister) cross by dist, dx.
  cuplPlotBins(...
    corrdist.ind.centres,...
    [corrdist.ind.m(:,lag),corrdist.sister.m(:,lag)],...
    [corrdist.ind.e(:,lag),corrdist.sister.e(:,lag)],plotOptions{:},...
    'PlotTitle',['Correlation by distance of all kinetochores, dx, lag ' num2str(lag-1)],...
    'Output',cuplMakeFigureName(an,num2str(lag-1,'corrdist-lag%d-all-bins')));
  
  % Plot pair centres cross by dist, dx.
  cuplPlotBins(...
    corrdist.pair.centres,corrdist.pair.m(:,lag),...
    corrdist.pair.e(:,lag),plotOptions{:},...
    'PlotTitle',['Correlation by distance of pair centres, dx ' num2str(lag-1)],...
    'Output',cuplMakeFigureName(an,num2str(lag-1,'corrdist-lag%d-centres-bins')));
end

% Plot distance histograms
if ismember('disthist',plots)
  dists = an.distances.sisters;
  plotOptions = {'PlotXLabel','Distance (um)',...
                 'plotYLabel','Density','NumBins',20};


  % Non-sister separation distances.
  cuplPlotHistogram(...
    dists.ind.d,plotOptions{:},...
    'PlotTitle','Distances between non-sisters',...
    'Output',cuplMakeFigureName(an,'dists-nonsisters'));

  % Sister separation.
  cuplPlotHistogram(...
    dists.sister.d,plotOptions{:},...
    'PlotTitle','Distances between non-sisters',...
    'Output',cuplMakeFigureName(an,'dists-sisters'));  
end

% Plot mean squared displacement
if ismember('msd',plots)
  emsd = an.msd.ensemble;
  tmsd = an.msd.time;
  plotOptions = {'Colours',an.plotOptions.colours,'PlotXLabel',...
                 'Time (s)','PlotYLabel','Mean square distance (\mum^2)'};

  % Plot ensemble average msd.
  cuplPlotBins(...
    an.time,emsd.m_d,emsd.e_d,plotOptions{:},...
    'PlotTitle','Mean squared displacement (ensemble avg)',...
    'Output',cuplMakeFigureName(an,'msd-ensemble'));  
  
  % Plot time average msd.
  cuplPlotBins(...
    an.time,tmsd.m_d,tmsd.e_d,plotOptions{:},...
    'PlotTitle','Mean squared displacement (time avg)',...
    'Output',cuplMakeFigureName(an,'msd-time'));  
end

% Plot speeds.
if ismember('speedhist',plots)
  % Speeds.
  cuplPlotHistogram(an.speeds.sisters.dx,'NumBins',20,...
                    'plotYLabel','Density',...
                    'plotXLabel','Normal speed (um/sec)',...
                    'PlotTitle','Average speeds',...
                    'Output',cuplMakeFigureName(an,'normal-speeds'));

  % Speeds by radius scatter.
  % cuplPlotScatter(an.acceptedRadii, an.speeds,...
  %                 'plotYLabel','Radius (\mum)',...
  %                 'plotXLabel','Speed (\mum/sec)',...
  %                 'PlotTitle','Speeds by radius',...
  %                 'Output',fullfile(an.outputDirectory,'speedsByRadius.pdf'));

end

% Plot phase shifts by distance.
if ismember('phaseshifts',plots)
  error('Unimplemented');

  % Average phase shifts scatter.
  cuplPlotScatter(...
    an.avgDisplacements.distances.c, ...
    an.avgDisplacements.c_x,...
    'plotYLabel','Displacement (\mum)',...
    'plotXLabel','Distance in plate plane (\mum)',...
    'PlotTitle','Relative displacement by distance',...
    'Output',fullfile(an.outputDirectory,'displacementByDist.pdf'));

  % Average relative displacement binned.
  cuplPlotBins(...
    an.avgDisplacements.bin_d.c_x.centres,...
    an.avgDisplacements.bin_d.c_x.m,...
    an.avgDisplacements.bin_d.c_x.se,...
    'plotYLabel','Displacement (\mum)',...
    'plotXLabel','Distance in plate plane (\mum)',...
    'PlotTitle','Relative displacement by distance',...
    'Output',fullfile(an.outputDirectory,'displacementByDistBinned.pdf'));
end

% Plot monopolar correlations by central angle.
if ismember('monopoleangle',plots)
  theta = an.monopole.angles.pair.theta;
  corrs = an.monopole.crosscorr;
  autocorrs = an.monopole.autocorr;
  corrangle = an.monopoleangle.sisters;
  lagzero = an.monopole.crosscorr.numLags+1;
  plotOptions = {'Colours',an.plotOptions.colours,...
                 'plotXLabel','Central angle (\theta)'};

  % Plot pair centres dr.
  cuplPlotScatter(...
    theta,corrs.pair.dr(lagzero,:)',plotOptions{:},...
    'PlotTitle','Monopolar correlation by central angle of pair centres, dr',...
    'Output',cuplMakeFigureName(an,'monopolecorrangle-centres'));

  % Plot pair centres cross by dist, dx.
  cuplPlotBins(...
    corrangle.pair.centres,corrangle.pair.m(:,lagzero),...
    corrangle.pair.e(:,lagzero),plotOptions{:},...
    'PlotTitle','Monopolar correlation by central angle of pair centres, dr',...
    'Output',cuplMakeFigureName(an,'monopolecorrangle-centres-bins'));

  % Plot dr autocorrelation.
  plotOptions = {'Colours',an.plotOptions.colours};
  cuplPlotCorrelation(...
    autocorrs.t,autocorrs.pair.m_dr,...
    autocorrs.pair.e_dr,plotOptions{:},...
    'PlotTitle','Average autocorrelation of monotelic pair centres, dr',...
    'Output',cuplMakeFigureName(an,'avg-autocorr-mono-dr'));

  % Plot projected centre displacement autocorrelation.
  projauto = an.autocorrs.proj.centre;
  cuplPlotCorrelation(...
    autocorrs.t,projauto.m_dr,...
    projauto.e_dr,plotOptions{:},...
    'PlotTitle','Average autocorrelation of pair centres under projection, dr',...
    'Output',cuplMakeFigureName(an,'avg-autocorr-proj-dr'));
end

% Record stage.
an.stages = union(an.stages,'plots');

% Unalias analysis.
analysis = an;

% Save analysis mat.
cuplSaveMat(analysis);
